var searchData=
[
  ['cad_20geometries_0',['ALICE-O2 GEANT Simulation of CAD Geometries',['../d8/d2b/md__2home_2runner_2work_2AliceO2_2AliceO2_2scripts_2geometry_2simulating__CAD__modules.html',1,'']]],
  ['cad_20to_20tgeo_20geometry_20import_1',['CAD-to-TGeo geometry import',['../d7/d38/md__2home_2runner_2work_2AliceO2_2AliceO2_2scripts_2geometry_2README.html',1,'']]],
  ['calibration_2',['calibration',['../dd/d61/refDetectorsMUONMCHCalibration.html',1,'Calibration'],['../de/d6c/refDetectorsTOFcalibration.html',1,'Calibration'],['../d2/dd2/refDetectorsCalibration.html',1,'Detectors Calibration'],['../d4/da4/refHMPIDcalibration.html',1,'HMPID calibration'],['../d0/d83/refTPCcalibrationIDC.html',1,'IDC Calibration'],['../d2/d8d/refDetectorsPHOScalibration.html',1,'PHOS Calibration'],['../d7/df0/refTPCcalibrationCalibdEdx.html',1,'Residual dEdx Calibration'],['../d9/d91/refTPCcalibrationCalibPadGainTracks.html',1,'Residual gainmap calibration'],['../d7/d91/refTPCcalibration.html',1,'TPC Calibration'],['../d3/dd4/refDetectorsTRDcalibration.html',1,'TRD calibration']]],
  ['calibration_20executable_3',['MID Calibration executable',['../d9/dd8/refMUONMIDCalibrationExe.html',1,'refDetectorsMUONMID']]],
  ['calibration_20macros_4',['MID Calibration macros',['../d6/de5/refMUONMIDCalibrationMacros.html',1,'']]],
  ['calibration_20testmacros_5',['Detectors/Calibration/testMacros',['../d4/d7a/refDetectorsCalibrationtestMacros.html',1,'refDetectorsCalibration']]],
  ['calibration_20workflow_6',['Calibration workflow',['../d0/d0d/refFITcommoncalibration.html',1,'refDetectorsFIT']]],
  ['calibration_20workflows_7',['calibration workflows',['../d2/dc3/refDetectorszdctestWorkflow.html',1,'Calibration Workflows'],['../d8/d9d/refMFT.html',1,'MFTcalibrationTestWorkflow MFT calibration workflows']]],
  ['calibrations_8',['Calibrations',['../da/db2/md__2home_2runner_2work_2AliceO2_2AliceO2_2Detectors_2FIT_2FT0_2calibration_2README.html',1,'']]],
  ['ccdb_9',['Module &apos;CCDB&apos;',['../d8/d62/refCCDB.html',1,'']]],
  ['claude_10',['CLAUDE',['../d6/db7/md__2home_2runner_2work_2AliceO2_2AliceO2_2CLAUDE.html',1,'']]],
  ['clion_11',['CLion',['../db/d32/refdocCLion.html',1,'refdoc']]],
  ['clustering_12',['clustering',['../d7/ded/refDetectorsMUONMCHClustering.html',1,'Clustering'],['../d4/d2d/refMUONMIDClustering.html',1,'MID Clustering'],['../d2/d4b/refDetectorsMUONMCHTimeClustering.html',1,'Time Clustering']]],
  ['cmake_20instructions_13',['CMake Instructions',['../d5/d61/refdocCMakeInstructions.html',1,'refdoc']]],
  ['cmake_20migration_14',['Modern CMake Migration',['../dd/d59/refdocModernCMakeMigration.html',1,'refdoc']]],
  ['code_20organization_15',['Code Organization',['../d3/d0e/refdocCodeOrganization.html',1,'refdoc']]],
  ['codec_16',['Raw CoDec',['../d4/dea/refDetectorsMUONMCHRaw.html',1,'refDetectorsMUONMCH']]],
  ['coding_20library_17',['Entropy Coding Library',['../de/da4/refUtilitiesrANS.html',1,'refUtilities']]],
  ['common_18',['common',['../d6/d1e/refDetectorsMUONCommon.html',1,'Common'],['../d8/d3e/refCommon.html',1,'Module &apos;Common&apos;']]],
  ['compilation_19',['run-time-compilation',['../df/d70/md__2home_2runner_2work_2AliceO2_2AliceO2_2GPU_2documentation_2run-time-compilation.html',1,'']]],
  ['conditions_20',['conditions',['../d9/d1e/refDetectorsMUONMCHConditions.html',1,'Conditions'],['../d2/d4e/refMFTcondition.html',1,'Conditions']]],
  ['configuration_20and_20scripts_21',['Full system test configuration and scripts',['../d3/df1/refprodtestsfull-system-test.html',1,'refdoc']]],
  ['configuration_20options_22',['Configuration options',['../df/da9/md__2home_2runner_2work_2AliceO2_2AliceO2_2prodtests_2full-system-test_2documentation_2dpl-workflow-options.html',1,'']]],
  ['contour_20library_23',['Contour Library',['../dc/d59/refDetectorsMUONMCHContour.html',1,'refDetectorsMUONMCH']]],
  ['contours_24',['Segmentation contours',['../d6/d23/refDetectorsMUONMCHMappingSegContour.html',1,'refDetectorsMUONMCHMapping']]],
  ['control_25',['Data Formats Quality Control',['../db/d9a/refDataFormatsQualityControl.html',1,'refDataFormats']]],
  ['conversion_26',['conversion',['../d3/dea/refDetectorsMUONMCHRawEncoderDigit.html',1,'Digit Conversion'],['../d8/d8d/md__2home_2runner_2work_2AliceO2_2AliceO2_2prodtests_2full-system-test_2documentation_2raw-tf-conversion.html',1,'raw-tf-conversion']]],
  ['converter_27',['ALICEO2dataModel converter',['../da/db9/refscriptsDatamodel-doc.html',1,'refscripts']]],
  ['cookbook_28',['Core COOKBOOK',['../db/dd3/refFrameworkCoreCOOKBOOK.html',1,'refFrameworkCore']]],
  ['core_29',['Core',['../d4/d0b/refFrameworkCore.html',1,'refFramework']]],
  ['core_20analysis_30',['Core ANALYSIS',['../de/d8c/refFrameworkCoreANALYSIS.html',1,'refFrameworkCore']]],
  ['core_20cookbook_31',['Core COOKBOOK',['../db/dd3/refFrameworkCoreCOOKBOOK.html',1,'refFrameworkCore']]],
  ['core_20profiling_32',['Core PROFILING',['../da/dc3/refFrameworkCorePROFILING.html',1,'refFrameworkCore']]],
  ['correction_33',['Average Distortion Correction',['../dc/d0f/refTPCcalibrationAverageDistortionCorrection.html',1,'refTPCcalibration']]],
  ['cpv_34',['CPV',['../d3/d25/refDetectorsCPV.html',1,'refDetectors']]],
  ['creation_35',['Creation',['../d7/d5b/refDetectorsMUONMCHGeometryCreator.html',1,'refDetectorsMUONMCHGeometry']]],
  ['ctf_20data_20handling_36',['CTF Data handling',['../d9/d66/refDetectorsCTF.html',1,'refDetectors']]],
  ['ctf_20encoding_20library_37',['ctf encoding library',['../dd/dd7/refDetectorsMUONMCHCTF.html',1,'MCH CTF encoding library'],['../d1/db3/refMUONMIDCTF.html',1,'MID CTF encoding library']]],
  ['ctp_20workflow_20scalers_38',['CTP Workflow Scalers',['../da/dce/refDetectorsCTP.html',1,'refDetectors']]]
];
